mongo_bots:
  uri: "mongodb://localhost:27017"
  ssl: false
  bots_db: ivan_bots
  tickets_db: ivan_bots-tickets
  sources_db: ivan_bots-sources-bots

mongo_parsers:
  uri: "mongodb://localhost:27017"
  ssl: false
  parsers_db: ivan_bots-parsers

spiders:
  loglevel: DEBUG
  log_enabled: TRUE
  bots:
    - etihadarena
  download_delay: 0.25
  download_timeout: 30
  retry_times: 5

celery:
  loglevel: DEBUG
  schedule:
    bots:
      seconds: 10
      default_delay: 60
#      expires: 120
      expires: 600
    wait:
      hour: '*'
      minute: '*'
      expires: 720

redis:
  host: localhost
  port: 6379
  password: ""
  celery_db: 1

main_proxy: ''